//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OesUI.ExamService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ExamService.IExamService")]
    public interface IExamService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IExamService/getExamById", ReplyAction="http://tempuri.org/IExamService/getExamByIdResponse")]
        OesWCFContract.ExamDS.examDataTable getExamById(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IExamService/getExamCount", ReplyAction="http://tempuri.org/IExamService/getExamCountResponse")]
        int getExamCount(string username, string keyword);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IExamService/InsertExanResultById", ReplyAction="http://tempuri.org/IExamService/InsertExanResultByIdResponse")]
        void InsertExanResultById(int userId, int examId, double score, string isPassed);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IExamService/SearchExam", ReplyAction="http://tempuri.org/IExamService/SearchExamResponse")]
        OesWCFContract.UserDS.SearchExamDataTable SearchExam(string sortName, string sortDirection, int currentPage, int pageSize, string keyword, string userName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IExamService/GetExceptionOccurTime", ReplyAction="http://tempuri.org/IExamService/GetExceptionOccurTimeResponse")]
        OesWCFContract.ExamDS.exam_exceptionDataTable GetExceptionOccurTime(int userId, int examId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IExamService/InsertExamExceptionTime", ReplyAction="http://tempuri.org/IExamService/InsertExamExceptionTimeResponse")]
        void InsertExamExceptionTime(int userId, int examId, System.DateTime dataTime);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IExamServiceChannel : OesUI.ExamService.IExamService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ExamServiceClient : System.ServiceModel.ClientBase<OesUI.ExamService.IExamService>, OesUI.ExamService.IExamService {
        
        public ExamServiceClient() {
        }
        
        public ExamServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ExamServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ExamServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ExamServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public OesWCFContract.ExamDS.examDataTable getExamById(int id) {
            return base.Channel.getExamById(id);
        }
        
        public int getExamCount(string username, string keyword) {
            return base.Channel.getExamCount(username, keyword);
        }
        
        public void InsertExanResultById(int userId, int examId, double score, string isPassed) {
            base.Channel.InsertExanResultById(userId, examId, score, isPassed);
        }
        
        public OesWCFContract.UserDS.SearchExamDataTable SearchExam(string sortName, string sortDirection, int currentPage, int pageSize, string keyword, string userName) {
            return base.Channel.SearchExam(sortName, sortDirection, currentPage, pageSize, keyword, userName);
        }
        
        public OesWCFContract.ExamDS.exam_exceptionDataTable GetExceptionOccurTime(int userId, int examId) {
            return base.Channel.GetExceptionOccurTime(userId, examId);
        }
        
        public void InsertExamExceptionTime(int userId, int examId, System.DateTime dataTime) {
            base.Channel.InsertExamExceptionTime(userId, examId, dataTime);
        }
    }
}
