//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OesUI.UserService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="UserService.IUserService")]
    public interface IUserService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserService/queryUserIdByName", ReplyAction="http://tempuri.org/IUserService/queryUserIdByNameResponse")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(OesWCFContract.UserNameNotExistent))]
        object queryUserIdByName(string name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserService/VerifyUserLogin", ReplyAction="http://tempuri.org/IUserService/VerifyUserLoginResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(OesWCFContract.UserNameNotExistent), Action="http://tempuri.org/IUserService/VerifyUserLoginUserNameNotExistentFault", Name="UserNameNotExistent", Namespace="http://schemas.datacontract.org/2004/07/OesWCFContract")]
        bool VerifyUserLogin(string username, string password);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IUserServiceChannel : OesUI.UserService.IUserService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class UserServiceClient : System.ServiceModel.ClientBase<OesUI.UserService.IUserService>, OesUI.UserService.IUserService {
        
        public UserServiceClient() {
        }
        
        public UserServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public UserServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UserServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UserServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public object queryUserIdByName(string name) {
            return base.Channel.queryUserIdByName(name);
        }
        
        public bool VerifyUserLogin(string username, string password) {
            return base.Channel.VerifyUserLogin(username, password);
        }
    }
}
